### ISSUE TITLE
Error logging issue with merge-bc-output.py

### ISSUE THREAD

**Issue by jatin-kala** [wegener-center/pyCAT#10]
Hi,
When i try to run merge-bc-oputput.py on the outputs generated from running the test case, i get the following error:

`Traceback (most recent call last):
  File "/data/Jatin/miniconda3/envs/pycat/bin/merge-bc-output.py", line 72, in <module>
    level=args.log_level, datefmt='%F %T'
  File "/data/Jatin/miniconda3/envs/pycat/lib/python3.7/logging/__init__.py", line 1888, in basicConfig
    raise ValueError("'stream' and 'filename' should not be "
ValueError: 'stream' and 'filename' should not be specified together`

It appears to be an issue with Python 3.7.x onwards it seems:
https://stackoverflow.com/questions/62102142/python-logging-in-console-and-log-file?noredirect=1&lq=1

Any ideas on how to overcome this? Can you reproduce it at your end?
Thanks in advance
Jatin

**Comment by mir06** [comment]
Yes, that's true. This is still python 2.7 code.

Just a quick work-around so that you can use the script:
- Edit https://github.com/wegener-center/pyCAT/blob/ef51ba7183ecdf02306182abe9effdefd02b718d/bin/merge-bc-output.py#L70  either remove `filename=` or `stream=` argument/
- run `python setup.py install` again

But feel free to submit a pull request.

**Comment by mir06** [comment]
Solved in reslease 1.1.1.
